before_install:
  - sudo apt-get -y -q install curl make libgc-dev
  - git clone --depth=1 git://github.com/fasterthanlime/rock.git 
  - (cd rock && make -s quick-rescue)
  - export PATH=$PATH:$PWD/rock/bin

script:
  - export OOC_LIBS=$PWD
  - cd samples
  - mkdir -p travis
  - rock -v prime -o=travis/prime && travis/prime
  - rock -v process -o=travis/process && echo "hello & goodbye" | travis/process

